---
require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

Gemspec/OrderedDependencies:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  Enabled: false
  EnforcedColonStyle: key
  EnforcedHashRocketStyle: key

Layout/ParameterAlignment:
  Enabled: false
  EnforcedStyle: with_first_parameter

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/HeredocIndentation:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false
  EnforcedStyle: aligned

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousOperator:
  Exclude:
  - app/graphql/**/*

Lint/SuppressedException:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: false

Lint/UnusedBlockArgument:
  Exclude:
  - app/graphql/**/*

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 10

Metrics/MethodLength:
  Enabled: true
  Max: 50

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/FileName:
  AllowedAcronyms:
  - HMAC
  - OAuth2
  Exclude:
  - lib/xero_hq/**/*
  - lib/**/*
  - gems/**/*
  - lib/http_errors.rb
  ExpectMatchingDefinition: true
  Include:
  - lib/**/*

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: true
  PreferredName: error

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/BeEql:
  Enabled: true

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/EmptyLineAfterSubject:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/ExpectChange:
  Enabled: true
  EnforcedStyle: block

RSpec/ExpectInHook:
  Enabled: false

RSpec/FilePath:
  Enabled: true
  Exclude:
  - spec/graphql/**/*.rb # TODO: Fix GQL tests

RSpec/Focus:
  Enabled: true

RSpec/HookArgument:
  Enabled: true
  EnforcedStyle: each

RSpec/HooksBeforeExamples:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/IteratedExpectation:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/LetBeforeExamples:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleSubjects:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NotToNot:
  Enabled: true

RSpec/OverwritingSetup:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/ReturnFromStub:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/UnspecifiedException:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/VoidExpect:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AndOr:
  Enabled: false
  Include:
  - lib/karbon_integration/**/*

Style/ClassAndModuleChildren:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: expanded

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false
  Include:
  - lib/payments/**/*

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys

Style/IfUnlessModifier:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false
  Include:
  - lib/karbon_integration/**/*

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses
  IgnoredPatterns:
    - include
    - require
    - require_relative
    - require_dependency
    - raise
    # Specs
    - to
    - not_to

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MixinUsage:
  Enabled: true
  Exclude:
  - spec/**/*_spec.rb

Style/ModuleFunction:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Not:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false
  Include:
  - lib/karbon_integration/**/*

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/Semicolon:
  Enabled: true

Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: true

Style/ZeroLengthPredicate:
  Enabled: false
